/**
 * Service Logos 配置（純資料檔案）
 *
 * 這是一個純資料配置檔案，只包含服務名稱到域名的對映。
 * 邏輯處理（URL生成、匹配演算法）由客戶端程式碼實現（src/ui/scripts/core.js）。
 *
 * 資料格式：服務名 → 域名
 * 例如：'google' → 'google.com'
 *
 * 客戶端會自動拼接 /api/favicon/ 字首生成完整的圖示 URL
 */

export const SERVICE_LOGOS = {
	// 科技巨頭
	google: 'google.com',
	'google cloud': 'cloud.google.com',
	microsoft: 'microsoft.com',
	'microsoft azure': 'azure.microsoft.com',
	apple: 'apple.com',
	'apple id': 'apple.com',
	amazon: 'amazon.com',
	meta: 'meta.com',
	facebook: 'facebook.com',

	// 社交媒體
	twitter: 'twitter.com',
	x: 'x.com',
	instagram: 'instagram.com',
	linkedin: 'linkedin.com',
	reddit: 'reddit.com',
	snapchat: 'snapchat.com',
	pinterest: 'pinterest.com',
	tiktok: 'tiktok.com',
	discord: 'discord.com',
	mastodon: 'joinmastodon.org',
	truthsocial: 'truthsocial.com',
	'truth social': 'truthsocial.com',

	// 通訊工具
	slack: 'slack.com',
	telegram: 'telegram.org',
	whatsapp: 'whatsapp.com',
	signal: 'signal.org',
	zoom: 'zoom.us',

	// 開發平臺
	github: 'github.com',
	gitee: 'gitee.com',
	gitlab: 'gitlab.com',
	bitbucket: 'bitbucket.org',

	// 雲服務商
	aws: 'aws.amazon.com',
	'amazon web services': 'aws.amazon.com',
	amazonaws: 'amazonaws.com',
	azure: 'azure.microsoft.com',
	gcp: 'cloud.google.com',
	googleapis: 'googleapis.com',
	cloudflare: 'cloudflare.com',
	cloudcone: 'cloudcone.com',
	digitalocean: 'digitalocean.com',
	linode: 'linode.com',
	vultr: 'vultr.com',
	heroku: 'heroku.com',
	vercel: 'vercel.com',
	netlify: 'netlify.com',
	render: 'render.com',
	railway: 'railway.app',
	'fly.io': 'fly.io',
	oracle: 'oracle.com',
	aliyun: 'alibabacloud.com',
	'tencent cloud': 'cloud.tencent.com',
	'huawei cloud': 'huaweicloud.com',

	// 開發工具
	docker: 'docker.com',
	kubernetes: 'kubernetes.io',
	jenkins: 'jenkins.io',
	travis: 'travis-ci.com',
	circleci: 'circleci.com',
	firebase: 'firebase.google.com',
	supabase: 'supabase.com',
	planetscale: 'planetscale.com',

	// 域名註冊商
	godaddy: 'godaddy.com',
	namecheap: 'namecheap.com',
	porkbun: 'porkbun.com',
	'name.com': 'name.com',
	dynadot: 'dynadot.com',

	// 生產力工具
	notion: 'notion.so',
	trello: 'trello.com',
	asana: 'asana.com',
	jira: 'atlassian.com',
	confluence: 'atlassian.com',
	monday: 'monday.com',
	airtable: 'airtable.com',

	// 設計工具
	figma: 'figma.com',
	canva: 'canva.com',
	adobe: 'adobe.com',

	// 雲端儲存
	dropbox: 'dropbox.com',
	onedrive: 'onedrive.live.com',
	'google drive': 'drive.google.com',
	box: 'box.com',

	// 密碼管理器
	'1password': '1password.com',
	bitwarden: 'bitwarden.com',
	lastpass: 'lastpass.com',
	dashlane: 'dashlane.com',

	// AI平臺
	openai: 'openai.com',
	chatgpt: 'openai.com',
	anthropic: 'anthropic.com',
	claude: 'anthropic.com',
	gemini: 'gemini.com',
	huggingface: 'huggingface.co',
	replicate: 'replicate.com',
	cohere: 'cohere.com',
	'stability ai': 'stability.ai',
	midjourney: 'midjourney.com',
	dalle: 'openai.com',
	bard: 'bard.google.com',
	perplexity: 'perplexity.ai',
	'character.ai': 'character.ai',
	poe: 'poe.com',

	// 支付平臺
	paypal: 'paypal.com',
	stripe: 'stripe.com',
	square: 'squareup.com',
	wise: 'wise.com',

	// 加密貨幣交易所
	binance: 'binance.com',
	coinbase: 'coinbase.com',
	kraken: 'kraken.com',
	bitfinex: 'bitfinex.com',
	okx: 'okx.com',
	huobi: 'huobi.com',
	kucoin: 'kucoin.com',
	bybit: 'bybit.com',

	// 遊戲平臺
	steam: 'steampowered.com',
	'epic games': 'epicgames.com',
	epicgames: 'epicgames.com',
	'battle.net': 'blizzard.com',
	blizzard: 'blizzard.com',
	ubisoft: 'ubisoft.com',
	ea: 'ea.com',
	origin: 'origin.com',
	'riot games': 'riotgames.com',
	activision: 'activision.com',
	playstation: 'playstation.com',
	xbox: 'xbox.com',
	nintendo: 'nintendo.com',

	// 流媒體
	netflix: 'netflix.com',
	spotify: 'spotify.com',
	youtube: 'youtube.com',
	twitch: 'twitch.tv',
	hulu: 'hulu.com',
	'disney+': 'disneyplus.com',
	hbo: 'hbo.com',
	'prime video': 'primevideo.com',

	// 電商平臺
	shopify: 'shopify.com',
	ebay: 'ebay.com',
	etsy: 'etsy.com',
	walmart: 'walmart.com',
	target: 'target.com',
	alibaba: 'alibaba.com',
	taobao: 'taobao.com',
	jd: 'jd.com',

	// 出行服務
	uber: 'uber.com',
	lyft: 'lyft.com',
	airbnb: 'airbnb.com',

	// 金融服務
	robinhood: 'robinhood.com',
	webull: 'webull.com',
	'charles schwab': 'schwab.com',

	// VPN服務
	nordvpn: 'nordvpn.com',
	expressvpn: 'expressvpn.com',
	protonvpn: 'protonvpn.com',

	// 郵箱服務
	gmail: 'gmail.com',
	outlook: 'outlook.com',
	protonmail: 'proton.me',
	proton: 'proton.me',
	yahoo: 'yahoo.com',

	// 內容平臺
	medium: 'medium.com',
	substack: 'substack.com',
	patreon: 'patreon.com',
	wordpress: 'wordpress.com',
	'greasy fork': 'greasyfork.org',
	greasyfork: 'greasyfork.org',

	// 其他工具
	duckduckgo: 'duckduckgo.com',
	mozilla: 'mozilla.org',
	brave: 'brave.com',
	evernote: 'evernote.com',
	bitly: 'bitly.com',
	salesforce: 'salesforce.com',
	hubspot: 'hubspot.com',

	// 中國服務
	tencent: 'tencent.com',
	wechat: 'wechat.com',
	alipay: 'alipay.com',
	baidu: 'baidu.com',
	douyin: 'douyin.com',
	bilibili: 'bilibili.com',
	xiaohongshu: 'xiaohongshu.com',
	dingding: 'dingtalk.com',
	feishu: 'feishu.cn',
	lark: 'larksuite.com',

	// 更多社交媒體和通訊
	threads: 'threads.net',
	bluesky: 'bsky.app',
	tumblr: 'tumblr.com',
	vk: 'vk.com',
	line: 'line.me',
	viber: 'viber.com',
	'wechat work': 'work.weixin.qq.com',
	skype: 'skype.com',
	messenger: 'messenger.com',
	teams: 'teams.microsoft.com',
	'google meet': 'meet.google.com',
	webex: 'webex.com',

	// 更多雲服務商
	ovh: 'ovh.com',
	hetzner: 'hetzner.com',
	scaleway: 'scaleway.com',
	contabo: 'contabo.com',
	ionos: 'ionos.com',
	'ibm cloud': 'cloud.ibm.com',
	upcloud: 'upcloud.com',
	kamatera: 'kamatera.com',
	hostinger: 'hostinger.com',
	dreamhost: 'dreamhost.com',
	bluehost: 'bluehost.com',
	siteground: 'siteground.com',
	a2hosting: 'a2hosting.com',
	hostgator: 'hostgator.com',
	inmotion: 'inmotionhosting.com',

	// 更多開發工具和服務
	npm: 'npmjs.com',
	yarn: 'yarnpkg.com',
	pnpm: 'pnpm.io',
	pip: 'pypi.org',
	pypi: 'pypi.org',
	composer: 'getcomposer.org',
	maven: 'maven.apache.org',
	gradle: 'gradle.org',
	nuget: 'nuget.org',
	cargo: 'crates.io',
	rubygems: 'rubygems.org',
	packagist: 'packagist.org',
	'go.dev': 'go.dev',
	rust: 'rust-lang.org',
	python: 'python.org',
	nodejs: 'nodejs.org',
	php: 'php.net',
	ruby: 'ruby-lang.org',
	java: 'java.com',

	// 監控和分析工具
	datadog: 'datadoghq.com',
	newrelic: 'newrelic.com',
	sentry: 'sentry.io',
	grafana: 'grafana.com',
	prometheus: 'prometheus.io',
	elastic: 'elastic.co',
	splunk: 'splunk.com',
	logstash: 'elastic.co',
	kibana: 'elastic.co',
	pagerduty: 'pagerduty.com',
	opsgenie: 'opsgenie.com',
	pingdom: 'pingdom.com',
	statuspage: 'statuspage.io',
	uptimerobot: 'uptimerobot.com',

	// 更多域名和 DNS 服務
	cloudns: 'cloudns.net',
	route53: 'aws.amazon.com',
	hover: 'hover.com',
	gandi: 'gandi.net',
	enom: 'enom.com',
	'domain.com': 'domain.com',
	'google domains': 'domains.google',
	spaceship: 'spaceship.com',

	// 更多加密貨幣和區塊鏈
	metamask: 'metamask.io',
	'trust wallet': 'trustwallet.com',
	ledger: 'ledger.com',
	trezor: 'trezor.io',
	exodus: 'exodus.com',
	'crypto.com': 'crypto.com',
	'gate.io': 'gate.io',
	bitget: 'bitget.com',
	mexc: 'mexc.com',
	bingx: 'bingx.com',
	phemex: 'phemex.com',
	bitmart: 'bitmart.com',
	poloniex: 'poloniex.com',
	bitstamp: 'bitstamp.net',

	// 更多支付平臺
	venmo: 'venmo.com',
	cashapp: 'cash.app',
	zelle: 'zellepay.com',
	revolut: 'revolut.com',
	n26: 'n26.com',
	monzo: 'monzo.com',
	chime: 'chime.com',
	payoneer: 'payoneer.com',
	skrill: 'skrill.com',
	neteller: 'neteller.com',
	adyen: 'adyen.com',
	braintree: 'braintreepayments.com',
	paddle: 'paddle.com',
	lemonsqueezy: 'lemonsqueezy.com',
	gumroad: 'gumroad.com',

	// 更多電商和市場
	mercari: 'mercari.com',
	poshmark: 'poshmark.com',
	depop: 'depop.com',
	vinted: 'vinted.com',
	rakuten: 'rakuten.com',
	wish: 'wish.com',
	aliexpress: 'aliexpress.com',
	tmall: 'tmall.com',
	pinduoduo: 'pinduoduo.com',
	lazada: 'lazada.com',
	shopee: 'shopee.com',
	tokopedia: 'tokopedia.com',
	carousell: 'carousell.com',

	// 教育平臺
	coursera: 'coursera.org',
	udemy: 'udemy.com',
	edx: 'edx.org',
	'khan academy': 'khanacademy.org',
	skillshare: 'skillshare.com',
	pluralsight: 'pluralsight.com',
	'linkedin learning': 'linkedin.com',
	udacity: 'udacity.com',
	codecademy: 'codecademy.com',
	freecodecamp: 'freecodecamp.org',
	leetcode: 'leetcode.com',
	hackerrank: 'hackerrank.com',
	codewars: 'codewars.com',
	topcoder: 'topcoder.com',
	kaggle: 'kaggle.com',

	// 更多流媒體和娛樂
	'apple music': 'music.apple.com',
	'apple tv': 'tv.apple.com',
	tidal: 'tidal.com',
	deezer: 'deezer.com',
	soundcloud: 'soundcloud.com',
	bandcamp: 'bandcamp.com',
	pandora: 'pandora.com',
	'youtube music': 'music.youtube.com',
	vimeo: 'vimeo.com',
	dailymotion: 'dailymotion.com',
	crunchyroll: 'crunchyroll.com',
	funimation: 'funimation.com',
	vrv: 'vrv.co',
	'paramount+': 'paramountplus.com',
	peacock: 'peacocktv.com',
	max: 'max.com',
	showtime: 'showtime.com',
	starz: 'starz.com',

	// 新聞和媒體
	nytimes: 'nytimes.com',
	wsj: 'wsj.com',
	'washington post': 'washingtonpost.com',
	guardian: 'theguardian.com',
	bbc: 'bbc.com',
	cnn: 'cnn.com',
	reuters: 'reuters.com',
	bloomberg: 'bloomberg.com',
	forbes: 'forbes.com',
	techcrunch: 'techcrunch.com',
	verge: 'theverge.com',
	wired: 'wired.com',
	'ars technica': 'arstechnica.com',
	'hacker news': 'news.ycombinator.com',

	// 論壇和社群
	'stack overflow': 'stackoverflow.com',
	stackoverflow: 'stackoverflow.com',
	'stack exchange': 'stackexchange.com',
	quora: 'quora.com',
	'4chan': '4chan.org',
	'8kun': '8kun.top',
	discourse: 'discourse.org',
	phpbb: 'phpbb.com',

	// 更多中國服務
	zhihu: 'zhihu.com',
	weibo: 'weibo.com',
	csdn: 'csdn.net',
	juejin: 'juejin.cn',
	segmentfault: 'segmentfault.com',
	oschina: 'oschina.net',
	cnblogs: 'cnblogs.com',
	'51cto': '51cto.com',
	infoq: 'infoq.cn',
	ithome: 'ithome.com',
	163: '163.com',
	netease: '163.com',
	qq: 'qq.com',
	360: '360.cn',
	sohu: 'sohu.com',
	sina: 'sina.com.cn',
	meituan: 'meituan.com',
	eleme: 'ele.me',
	didi: 'didiglobal.com',
	bytedance: 'bytedance.com',
	kuaishou: 'kuaishou.com',
	iqiyi: 'iqiyi.com',
	youku: 'youku.com',
	toutiao: 'toutiao.com',

	// 日本服務
	'line pay': 'pay.line.me',
	paypay: 'paypay.ne.jp',
	mercoin: 'mercoin.com',
	'yahoo japan': 'yahoo.co.jp',
	dmm: 'dmm.com',
	niconico: 'nicovideo.jp',
	pixiv: 'pixiv.net',

	// 韓國服務
	naver: 'naver.com',
	kakao: 'kakao.com',
	kakaotalk: 'kakao.com',
	coupang: 'coupang.com',
	bithumb: 'bithumb.com',
	upbit: 'upbit.com',

	// 俄羅斯服務
	vkontakte: 'vk.com',
	'telegram messenger': 'telegram.org',
	'mail.ru': 'mail.ru',
	'yandex mail': 'yandex.ru',
	rambler: 'rambler.ru',

	// 印度服務
	paytm: 'paytm.com',
	phonepe: 'phonepe.com',
	gpay: 'pay.google.com',
	flipkart: 'flipkart.com',
	'amazon india': 'amazon.in',
	swiggy: 'swiggy.com',
	zomato: 'zomato.com',
	ola: 'olacabs.com',

	// 東南亞服務
	grab: 'grab.com',
	gojek: 'gojek.com',
	bukalapak: 'bukalapak.com',

	// 更多VPN和安全服務
	surfshark: 'surfshark.com',
	cyberghost: 'cyberghostvpn.com',
	privateinternetaccess: 'privateinternetaccess.com',
	pia: 'privateinternetaccess.com',
	mullvad: 'mullvad.net',
	ivpn: 'ivpn.net',
	windscribe: 'windscribe.com',
	tunnelbear: 'tunnelbear.com',
	'hotspot shield': 'hotspotshield.com',

	// 更多密碼管理器
	keepass: 'keepass.info',
	keepassxc: 'keepassxc.org',
	nordpass: 'nordpass.com',
	roboform: 'roboform.com',
	enpass: 'enpass.io',
	keeper: 'keepersecurity.com',
	'zoho vault': 'zoho.com',

	// 更多設計和創意工具
	sketch: 'sketch.com',
	invision: 'invisionapp.com',
	miro: 'miro.com',
	lucidchart: 'lucidchart.com',
	whimsical: 'whimsical.com',
	excalidraw: 'excalidraw.com',
	'draw.io': 'draw.io',
	pixlr: 'pixlr.com',
	photopea: 'photopea.com',
	'remove.bg': 'remove.bg',

	// 更多郵件服務
	fastmail: 'fastmail.com',
	tutanota: 'tutanota.com',
	'mailbox.org': 'mailbox.org',
	'zoho mail': 'zoho.com',
	'yandex.mail': 'yandex.com',
	aol: 'aol.com',
	icloud: 'icloud.com',
	hey: 'hey.com',

	// 文件和協作工具
	'google docs': 'docs.google.com',
	'google sheets': 'sheets.google.com',
	'google slides': 'slides.google.com',
	'office 365': 'office.com',
	coda: 'coda.io',
	clickup: 'clickup.com',
	basecamp: 'basecamp.com',
	wrike: 'wrike.com',
	smartsheet: 'smartsheet.com',
	teamwork: 'teamwork.com',

	// 更多遊戲相關
	gog: 'gog.com',
	'itch.io': 'itch.io',
	'humble bundle': 'humblebundle.com',
	rockstar: 'rockstargames.com',
	'2k games': '2k.com',
	bethesda: 'bethesda.net',
	'square enix': 'square-enix.com',
	paradox: 'paradoxplaza.com',

	// 特殊服務
	redotpay: 'redotpay.com',
	v2ex: 'v2ex.com',
	yandex: 'yandex.com',
	deno: 'deno.com',
	bun: 'bun.sh',

	// 社群論壇
	'linux.do': 'linux.do',
};

// Cross-domain aliases for services that share one account ecosystem.
// Same-domain subservices (for example aws.amazon.com) are resolved automatically.
export const SERVICE_FAMILY_ALIASES = {
	'amazon.in': 'amazon.com',
	'amazonaws.com': 'amazon.com',
	'domains.google': 'google.com',
	'gmail.com': 'google.com',
	'googleapis.com': 'google.com',
	'icloud.com': 'apple.com',
	'onedrive.live.com': 'microsoft.com',
	'office.com': 'microsoft.com',
	'outlook.com': 'microsoft.com',
	'primevideo.com': 'amazon.com',
	'protonvpn.com': 'proton.me',
	'twitter.com': 'x.com',
	'work.weixin.qq.com': 'wecom.cn',
	'youtube.com': 'google.com',
};

// Display names are only needed when several differently named services merge.
export const SERVICE_FAMILY_NAMES = {
	'amazon.com': 'Amazon',
	'anthropic.com': 'Anthropic',
	'apple.com': 'Apple',
	'atlassian.com': 'Atlassian',
	'bitbucket.org': 'Bitbucket',
	'blizzard.com': 'Blizzard',
	'discord.com': 'Discord',
	'epicgames.com': 'Epic Games',
	'github.com': 'GitHub',
	'gitlab.com': 'GitLab',
	'google.com': 'Google',
	'microsoft.com': 'Microsoft',
	'openai.com': 'OpenAI',
	'paypal.com': 'PayPal',
	'proton.me': 'Proton',
	'wecom.cn': 'WeChat Work',
	'x.com': 'X',
};

// Only these high-confidence names may match a prefixed or camel-cased label.
// Every SERVICE_LOGOS entry still participates in exact-name aggregation.
export const SERVICE_FUZZY_MATCH_KEYS = [
	'amazon',
	'amazon india',
	'amazonaws',
	'amazon web services',
	'anthropic',
	'apple id',
	'aws',
	'azure',
	'battle.net',
	'bitbucket',
	'blizzard',
	'chatgpt',
	'claude',
	'confluence',
	'discord',
	'epic games',
	'epicgames',
	'firebase',
	'gcp',
	'github',
	'gitlab',
	'gmail',
	'google',
	'google cloud',
	'google docs',
	'google drive',
	'google meet',
	'google sheets',
	'google slides',
	'googleapis',
	'icloud',
	'jira',
	'microsoft',
	'microsoft azure',
	'office 365',
	'onedrive',
	'openai',
	'outlook',
	'paypal',
	'prime video',
	'proton',
	'protonmail',
	'protonvpn',
	'route53',
	'teams',
	'youtube',
	'youtube music',
];
